name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install dependencies
      run: dotnet restore

    - name: Install tools
      run: dotnet tool install --global coverlet.console

    - name: Build debug
      run: dotnet build --configuration Debug --no-restore

    - name: Testing
      run: coverlet CuentaBancaria.UnitTests/bin/Debug/net7/CuentaBancaria.UnitTests.dll --target "dotnet" --targetargs "test CuentaBancaria.UnitTests/CuentaBancaria.UnitTests.csproj --no-build --verbosity quiet" --format OpenCover --output cuentabancaria.coverage.xml

    - name: Upload
      run: bash <(curl -s https://codecov.io/bash)

    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: ./*.coverage.xml
